# Generated by Django 4.1.2 on 2022-10-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
